# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rnode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rnode.proto',
  package='coop.rchain.node',
  syntax='proto3',
  serialized_pb=_b('\n\x0brnode.proto\x12\x10\x63oop.rchain.node\"\x12\n\x10ListPeersRequest\".\n\x05Peers\x12%\n\x05peers\x18\x01 \x03(\x0b\x32\x16.coop.rchain.node.Peer\"/\n\x04Peer\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\x0c\"\x1a\n\nCmdRequest\x12\x0c\n\x04line\x18\x01 \x01(\t\"\x1f\n\x0b\x45valRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"\x1e\n\x0cReplResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2\x96\x01\n\x04Repl\x12\x45\n\x03Run\x12\x1c.coop.rchain.node.CmdRequest\x1a\x1e.coop.rchain.node.ReplResponse\"\x00\x12G\n\x04\x45val\x12\x1d.coop.rchain.node.EvalRequest\x1a\x1e.coop.rchain.node.ReplResponse\"\x00\x32Y\n\x0b\x44iagnostics\x12J\n\tListPeers\x12\".coop.rchain.node.ListPeersRequest\x1a\x17.coop.rchain.node.Peers\"\x00\x62\x06proto3')
)




_LISTPEERSREQUEST = _descriptor.Descriptor(
  name='ListPeersRequest',
  full_name='coop.rchain.node.ListPeersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=51,
)


_PEERS = _descriptor.Descriptor(
  name='Peers',
  full_name='coop.rchain.node.Peers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers', full_name='coop.rchain.node.Peers.peers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=99,
)


_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='coop.rchain.node.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='coop.rchain.node.Peer.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='coop.rchain.node.Peer.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='coop.rchain.node.Peer.key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=148,
)


_CMDREQUEST = _descriptor.Descriptor(
  name='CmdRequest',
  full_name='coop.rchain.node.CmdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='coop.rchain.node.CmdRequest.line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=176,
)


_EVALREQUEST = _descriptor.Descriptor(
  name='EvalRequest',
  full_name='coop.rchain.node.EvalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='coop.rchain.node.EvalRequest.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=209,
)


_REPLRESPONSE = _descriptor.Descriptor(
  name='ReplResponse',
  full_name='coop.rchain.node.ReplResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='coop.rchain.node.ReplResponse.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=241,
)

_PEERS.fields_by_name['peers'].message_type = _PEER
DESCRIPTOR.message_types_by_name['ListPeersRequest'] = _LISTPEERSREQUEST
DESCRIPTOR.message_types_by_name['Peers'] = _PEERS
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.message_types_by_name['CmdRequest'] = _CMDREQUEST
DESCRIPTOR.message_types_by_name['EvalRequest'] = _EVALREQUEST
DESCRIPTOR.message_types_by_name['ReplResponse'] = _REPLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListPeersRequest = _reflection.GeneratedProtocolMessageType('ListPeersRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPEERSREQUEST,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.ListPeersRequest)
  ))
_sym_db.RegisterMessage(ListPeersRequest)

Peers = _reflection.GeneratedProtocolMessageType('Peers', (_message.Message,), dict(
  DESCRIPTOR = _PEERS,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.Peers)
  ))
_sym_db.RegisterMessage(Peers)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), dict(
  DESCRIPTOR = _PEER,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.Peer)
  ))
_sym_db.RegisterMessage(Peer)

CmdRequest = _reflection.GeneratedProtocolMessageType('CmdRequest', (_message.Message,), dict(
  DESCRIPTOR = _CMDREQUEST,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.CmdRequest)
  ))
_sym_db.RegisterMessage(CmdRequest)

EvalRequest = _reflection.GeneratedProtocolMessageType('EvalRequest', (_message.Message,), dict(
  DESCRIPTOR = _EVALREQUEST,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.EvalRequest)
  ))
_sym_db.RegisterMessage(EvalRequest)

ReplResponse = _reflection.GeneratedProtocolMessageType('ReplResponse', (_message.Message,), dict(
  DESCRIPTOR = _REPLRESPONSE,
  __module__ = 'rnode_pb2'
  # @@protoc_insertion_point(class_scope:coop.rchain.node.ReplResponse)
  ))
_sym_db.RegisterMessage(ReplResponse)



_REPL = _descriptor.ServiceDescriptor(
  name='Repl',
  full_name='coop.rchain.node.Repl',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=244,
  serialized_end=394,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='coop.rchain.node.Repl.Run',
    index=0,
    containing_service=None,
    input_type=_CMDREQUEST,
    output_type=_REPLRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Eval',
    full_name='coop.rchain.node.Repl.Eval',
    index=1,
    containing_service=None,
    input_type=_EVALREQUEST,
    output_type=_REPLRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPL)

DESCRIPTOR.services_by_name['Repl'] = _REPL


_DIAGNOSTICS = _descriptor.ServiceDescriptor(
  name='Diagnostics',
  full_name='coop.rchain.node.Diagnostics',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=396,
  serialized_end=485,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListPeers',
    full_name='coop.rchain.node.Diagnostics.ListPeers',
    index=0,
    containing_service=None,
    input_type=_LISTPEERSREQUEST,
    output_type=_PEERS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIAGNOSTICS)

DESCRIPTOR.services_by_name['Diagnostics'] = _DIAGNOSTICS

# @@protoc_insertion_point(module_scope)
