dist: trusty
env:
  - SUBPROJECT=comm
  - SUBPROJECT=rholang
  - SUBPROJECT=roscala
  - SUBPROJECT=rosette
  - SUBPROJECT=storage
script: ./scripts/build-subproject.sh
install: ./scripts/install.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
