language: scala
scala:
  - 2.12.3
sbt_args: -no-colors
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
env:
  - SUBPROJECT=comm
  - SUBPROJECT=rholang
  - SUBPROJECT=roscala
  - SUBPROJECT=rosette
  - SUBPROJECT=storage
script: ./scripts/build-subproject.sh
sudo: required
install: ./scripts/install.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
